# Generated by Django 6.0.6 on 2026-06-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_remove_product_membership_and_more'),
    ]

    operations = [
        # migrations.RunSQL("""
        #     INSERT INTO store_collection (title)
        #     VALUES ('collection1')
        # """, """
        #     DELETE FROM store_collection
        #     WHERE title = 'collection1 '
        # """)
    ]
